version: '3.7'

services:
  nacos:
    image: 'nacos/nacos-server:v2.1.0-slim'
    container_name: nacos
    privileged: true
    ports:
      - "0.0.0.0:8848:8848"
    environment:
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=node01.zaqbest.com
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_dev
      - MYSQL_SERVICE_USER=XXXXXXXXXXXXXXX
      - MYSQL_SERVICE_PASSWORD=XXXXXXXXXXXXXXX
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true