version: '3.7'
services:
  kafka-map:
    image: dushixiang/kafka-map:latest
    container_name: "kafka-map"
    restart: always
    volumes:
      - ./kafka-map-data:/usr/local/kafka-map/data
    ports:
      - 8082:8080
    environment:
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=rikei@1234
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://node02.zaqbest.com:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./kafka-data:/kafka
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ./zk_data:/data
    ports:
      - 2182:2181