version: '3.7'

services:
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: rabbitmq
    privileged: true
    volumes:
      - ./data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    environment:
      - RABBITMQ_DEFAULT_USER=XXXXXXXXXXXXXXX
      - RABBITMQ_DEFAULT_PASS=XXXXXXXXXXXXXXX